// --- Reflection / reward loop ---
function renderOutcomeOptions(){const el=$('#outcomeOption');el.innerHTML=state.decision.options.map((o,i)=>`<option value="${i}">${esc(o.name)}</option>`).join('')}
function recordOutcome(){const oi=Number($('#outcomeOption').value),sat=Number($('#outcomeSatisfaction').value),quality=Number($('#outcomeQuality').value),note=$('#outcomeNote').value.trim();const utility=calculateResults()[0];const reward=(sat+quality)/200;state.learning.outcomes.unshift({id:uid(),decision:state.decision.name,optionIndex:oi,satisfaction:sat,quality,note,t:Date.now(),reward});state.learning.outcomes=state.learning.outcomes.slice(0,100);const observed=state.learning.optionLatents[oi]||{score:0,variance:.9,evidence:0};const prediction=sigmoid(observed.score);observed.score+=(reward-prediction)*.55;observed.variance=clamp(observed.variance*.93,.04,1);observed.evidence++;state.learning.optionLatents[oi]=observed;const criterionImpact=state.decision.criteria.map((c,ci)=>normalizedScore(oi,ci));criterionImpact.forEach((signal,ci)=>{const name=state.decision.criteria[ci].name;const prior=state.learning.conceptMemory[canonicalConcept(name)];const desired=reward*(.4+.6*signal);rememberConcept(name,desired)});save();$('#outcomeNote').value='';renderAll();setTab('reflect')}
function renderReflection(){const out=state.learning.outcomes||[];$('#reflectionTrace').innerHTML=out.length?out.slice(0,5).map(o=>`<div class="trace-item"><strong>${esc(o.decision)}</strong> · ${esc(state.decision.options[o.optionIndex]?.name||'Option')}<br>Satisfaction ${o.satisfaction}/100 · Outcome quality ${o.quality}/100 · reward ${(o.reward*100).toFixed(0)}%</div>`).join(''):'<div class="empty">No outcome feedback yet.</div>';$('#journal').innerHTML=out.length?out.map(o=>`<div class="journal-item"><div><strong>${esc(o.decision)}</strong><span>${esc(state.decision.options[o.optionIndex]?.name||'Option')}</span></div><div><span>${new Date(o.t).toLocaleDateString()}</span><strong>${Math.round(o.reward*100)}%</strong></div></div>`).join(''):'<div class="empty">Your decision journal will appear here after the first outcome.</div>'}

function saveDecision(){syncInputs();ensureLatents();const snapshot={name:state.decision.name,context:state.decision.context,horizon:state.decision.horizon,risk:state.decision.risk,options:structuredClone(state.decision.options),criteria:structuredClone(state.decision.criteria),scores:structuredClone(state.decision.scores),results:calculateResults()};state.history.unshift({id:uid(),at:Date.now(),snapshot});state.history=state.history.slice(0,50);save()}
function renderMemory(){ensureLatents();const w=criterionWeights();$('#memoryProfile').innerHTML=state.decision.criteria.map((c,i)=>`<div class="memory-chip"><span>${esc(c.name)} <small>${state.learning.criterionLatents[i].evidence||0} evidence</small></span><strong>${fmt(w[i]*100)}</strong></div>`).sort((a,b)=>0).join('')||'<div class="empty">No learned preferences yet.</div>';const entries=Object.values(state.learning.conceptMemory||{}).sort((a,b)=>b.count-a.count).slice(0,12);$('#semanticMemory').innerHTML=entries.map(m=>`<div class="memory-chip"><span>${esc(m.label)}<small>${m.count} updates</small></span><strong>${Math.round(m.mean*100)}%</strong></div>`).join('')||'<div class="empty">Semantic concepts will appear as you learn.</div>'}

function loadDemo(){state.decision={name:'Choose a new laptop',context:'Need a laptop for development, study and travel. I care about long-term reliability but still need strong performance.',horizon:'long',risk:'balanced',options:[{name:'Zenbook 14'},{name:'ThinkPad X1'},{name:'MacBook Air'}],criteria:[{name:'Price',direction:'lower'},{name:'Performance',direction:'higher'},{name:'Battery life',direction:'higher'},{name:'Reliability',direction:'higher'},{name:'Portability',direction:'higher'}],scores:{'0:0':65,'0:1':82,'0:2':88,'0:3':76,'0:4':92,'1:0':55,'1:1':91,'1:2':71,'1:3':92,'1:4':74,'2:0':58,'2:1':86,'2:2':97,'2:3':89,'2:4':96}};state.learning={comparisons:[],criterionLatents:{},optionLatents:{},seenQuestions:[],conceptMemory:{},globalSignals:{},outcomes:[]};state.history=[];state.scenarios=[];state.simulation=null;save();renderAll();setTab('setup')}
function reset(){localStorage.removeItem(STORAGE_KEY);location.reload()}
function exportProfile(){const payload={version:2,exportedAt:now(),learning:state.learning,history:state.history,scenarios:state.scenarios};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='decision-lab-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importProfile(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.learning)throw new Error('missing learning');state.learning=Object.assign(state.learning,x.learning);state.history=x.history||state.history;state.scenarios=x.scenarios||state.scenarios;save();renderAll();alert('Profile imported.')}catch(e){alert('Invalid Decision Lab profile.')}};r.readAsText(file)}
function clearMemory(){state.learning={comparisons:[],criterionLatents:{},optionLatents:{},seenQuestions:[],conceptMemory:{},globalSignals:{},outcomes:[]};save();renderAll()}
function setTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));if(name==='learn')renderLearning();if(name==='analyze')renderAnalysis();if(name==='simulate')renderSimulation();if(name==='reflect'){renderOutcomeOptions();renderReflection()}if(name==='memory')renderMemory()}
function renderAll(){updateHeaderStats();renderSetup();renderPreferenceBars();renderLearning();renderAnalysis();renderSimulation();renderOutcomeOptions();renderReflection();renderMemory()}

$$('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('#resetBtn').onclick=reset;$('#demoBtn').onclick=loadDemo;$('#exportBtn').onclick=exportProfile;$('#clearMemoryBtn').onclick=()=>{if(confirm('Clear learned preferences and outcome memory?'))clearMemory()};$('#importInput').onchange=e=>e.target.files[0]&&importProfile(e.target.files[0]);
$('#jumpBuildBtn').onclick=()=>setTab('setup');$('#howItWorksBtn').onclick=()=>{$('#howModal').classList.add('open');$('#howModal').setAttribute('aria-hidden','false')};$('#closeHow').onclick=()=>{$('#howModal').classList.remove('open');$('#howModal').setAttribute('aria-hidden','true')};
$('#addOptionBtn').onclick=()=>{state.decision.options.push({name:`Option ${String.fromCharCode(65+state.decision.options.length)}`});save();renderSetup()};$('#addCriterionBtn').onclick=()=>{state.decision.criteria.push({name:`Criterion ${state.decision.criteria.length+1}`,direction:'higher'});save();renderSetup()};
$('#startLearningBtn').onclick=()=>{syncInputs();ensureLatents();saveDecision();setTab('learn')};$('#runSimulationBtn').onclick=()=>{runSimulation();setTab('simulate')};$('#recordOutcomeBtn').onclick=recordOutcome;$('#satisfactionValue').textContent=$('#outcomeSatisfaction').value;$('#qualityValue').textContent=$('#outcomeQuality').value;
$('#outcomeSatisfaction').oninput=e=>$('#satisfactionValue').textContent=e.target.value;$('#outcomeQuality').oninput=e=>$('#qualityValue').textContent=e.target.value;
$('#addScenarioBtn').onclick=()=>{const name=prompt('Scenario name','Long-term reliability focus');if(!name)return;const multipliers=state.decision.criteria.map(c=>1);const focus=prompt(`Optional criterion to emphasize (exact name).`,'');const idx=state.decision.criteria.findIndex(c=>c.name.toLowerCase()===String(focus).toLowerCase());if(idx>=0)multipliers[idx]=1.7;state.scenarios.push({id:uid(),name,note:focus?`Emphasizes ${focus}`:'Custom scenario',weights:multipliers});save();renderAnalysis()};
document.addEventListener('click',e=>{if(e.target.dataset.removeOption){state.decision.options.splice(+e.target.dataset.removeOption,1);reindexScores();save();renderSetup()}if(e.target.dataset.removeCriterion){state.decision.criteria.splice(+e.target.dataset.removeCriterion,1);reindexScores();save();renderSetup()}if(e.target.dataset.removeScenario){state.scenarios.splice(+e.target.dataset.removeScenario,1);save();renderAnalysis()}});
document.addEventListener('input',e=>{if(e.target.matches('input,textarea,select')&&e.target.id!=='outcomeSatisfaction'&&e.target.id!=='outcomeQuality')syncInputs()});document.addEventListener('change',e=>{if(e.target.matches('select,input[type=number]'))syncInputs()});
function reindexScores(){const old={...state.decision.scores},next={};state.decision.options.forEach((_,oi)=>state.decision.criteria.forEach((_,ci)=>{const v=old[`${oi}:${ci}`];if(v!=null)next[`${oi}:${ci}`]=v}));state.decision.scores=next}
load();renderAll();
